server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3300/smbms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://foo:123456@localhost:27017/smbms

mybatis:
  type-aliases-package: com.chy.pojo
  mapper-locations: classpath:/mapper/*.xml
